### ISSUE TITLE
S337AP Not fully Supported

### ISSUE THREAD

**Issue by RobertHerreraEECS** [FirmWire/FirmWire#43]
The following is output when running on the CP_A515U1UES7CVD1

```
root@fd32070205ed:/firmwire# python3 firmwire.py modem.bin
              ___            __      _                          
-.     .-.   | __|(+) _ _ _ _\ \    / /(+) _ _ ___    .-.     .-
  \   /   \  | _|  | | '_| '  \ \/\/ /  | | '_/ -_)  /   \   /  
   '-'     '-|_|   | |_| |_|_|_\_/\_/   | |_| \___|-'     '-'   
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   v1.1.0
                A  baseband  analysis  platform
                   https://github.com/FirmWire

[INFO] firmwire.loader: Reading firmware using ShannonLoader (shannon)
Traceback (most recent call last):
  File "firmwire.py", line 312, in <module>
    sys.exit(main())
  File "firmwire.py", line 228, in main
    loader = firmwire.loader.load_any(
  File "/firmwire/firmwire/loader.py", line 142, in load_any
    obj = _do_load(loader_cls, path, workspace, **loader_args)
  File "/firmwire/firmwire/loader.py", line 184, in _do_load
    if obj.try_load():
  File "/firmwire/firmwire/vendor/shannon/loader.py", line 72, in try_load
    if not self.guess_soc_version():
  File "/firmwire/firmwire/vendor/shannon/loader.py", line 443, in guess_soc_version
    soc_date = int(found.group().split(b"SGCS_QB")[-1])
ValueError: invalid literal for int() with base 10: b'S337AP_S_20200120_033414'

```
I've tried editing the parsing manually but there seems to be a lot of issues with this variant of modem image. After attempting to hot patch this issue by changing `soc_date = int(found.group().split(b"SGCS_QB")[-1])` to `soc_date = int(found.group().split(b"_")[-2])` I get further along but then crash here:

```
[INFO] firmwire.emulator.patterndb: Found symbol SYM_SCHEDULABLE_TASK_LIST -> 0480222c [CACHED]
[INFO] firmwire.emulator.patterndb: Found symbol SYM_CUR_TASK_ID -> 04800ed0 [CACHED]
[INFO] firmwire.emulator.patterndb: Found symbol SYM_FN_EXCEPTION_SWITCH -> 40e526c4 [CACHED]
[INFO] firmwire.emulator.patterndb: Found symbol SYM_QUEUE_LIST -> 4017bf30 [CACHED]
[INFO] firmwire.emulator.patterndb: Skipping symbol QUIRK_SXXXAP_DVFS_HACK for S337AP
[WARN] firmwire.emulator.patterndb: Unable to resolve required dynamic symbol QUIRK_S337AP_SHM_HACK
[ERROR] firmwire.vendor.shannon.loader: Error resolving symbols
Traceback (most recent call last):
  File "/firmwire/firmwire/vendor/shannon/loader.py", line 94, in try_load
    db.find_patterns(main_toc.data, main_toc.load_address)
  File "/firmwire/firmwire/emulator/patterndb.py", line 142, in find_patterns
    address = self._find_pattern(data, offset, name, entry)
  File "/firmwire/firmwire/emulator/patterndb.py", line 230, in _find_pattern
    raise ValueError("Symbol resolution")
ValueError: Symbol resolution
[ERROR] firmwire.loader: Loading failed!
[ERROR] firmwire.loader: No more loaders to try
[ERROR] firmwire: Failed to load firmware
root@fd32070205ed:/firmwire# 
```

Seems like patterdb is failing to resolve some sort of work around QUIRK when retrieving specific symbols and subsequently failing thereafter.

**Comment by mariusmue** [comment]
I somehow overlooked this issue - but I believe the underlying issue was addressed with https://github.com/FirmWire/FirmWire/commit/77c0b55be7c19a78ae582c660ef833ef1eba7c84

This should be merged into mainline in the upcoming weeks.
